(define three 3)
(define (RectArea base height)
  (* base height)
  )
(define (printVal x)
  (begin
    (display x)
    (newline)
    x)
  )
(define (RectVol base height)
  (* (printVal (RectArea base height)) (read))
  )
(define (DiffVolume base1 height1 base2 height2)
  (- (RectVol base1 height1) (RectVol base2 height2))
  )
(define (RectAreaLet base height)
  (let ((b base)
        (h height))
    (* b h)
    )
  )
(define (RectVolLet base height)
  (let ((b base)
        (h height))
    (* (* b h) (read))
    )
  )
   
(+ (+ three 5) 7)
(+ (+ (+ three three) 5) 7)
(+ (* three 2) (* (* three 8) 8))
(+ (+ (* three 2) (* 9 9)) (/ 18 three))
(/ (+ (+ (+ (+ (+ (+ 2 three) 6) 8) 10) 12) 14) (+ (+ 2 three) 6))
